# Generated by Django 4.1.4 on 2023-11-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='rname',
        ),
    ]
